### ISSUE TITLE
Stickers on Whatsapp Desktop

### ISSUE THREAD

**Issue by ptkdev** [WhatsApp/stickers#210]
How is procedure for publish stickers on whatsapp desktop / web whatsapp?

**Comment by Alex193a** [comment]
At the moment third party stickers are not supported in WhatsApp Web/Desktop.
In the future will be fetched the stickers from your phone like the official ones.

**Comment by ptkdev** [comment]
Nice!

**Comment by simonzhexu** [comment]
We are going to support it. Just not yet.

**Comment by tomassouto** [comment]
Any new with this feature?

**Comment by ars4l4n** [comment]
come on guys, just add the stickers

**Comment by melquichaves** [comment]
Stickers, stickers, stickers \o\

**Comment by MarvinJWendt** [comment]
> We are going to support it. Just not yet.

To everybody who wants stickers to work on the Desktop version of WhatsApp:
It will most likely take some time, but instead of commenting here you can react to the original request with a `👍`.

**Comment by kichappa** [comment]
Any updates? It's been a year

**Comment by Alex193a** [comment]
> Any updates? It's been a year

Third-party stickers are supported by WhatsApp web/Desktop since November 2019 😅

**Comment by kichappa** [comment]
> > Any updates? It's been a year
> 
> Third-party stickers are supported by WhatsApp web/Desktop since November 2019 😅

Oh, I was looking for adding custom ```.webp``` files as a sticked through WhatsApp Web. Any ideas if that is available?

**Comment by Alex193a** [comment]
> Oh, I was looking for adding custom `.webp` files as a sticker through WhatsApp Web. Any ideas if that is available?

That's not possible and probably won't be in the future either.

**Comment by ars4l4n** [comment]
well they just take ages to load
also, you still can't sort your stickers inside the app besides marking
some as favorites. The rest of your stickers will be hard to browse through
if you have a lot of sticker packs from the play store. (I also couldn't
just grab single stickers from those sticker packs which I downloaded. Was
always forced to install the entire pack)

Don't you guys have facebook to back you up with budged? Why is Whatsapp so
suboptimal? (also considering the other functions whatsapp web doesn't have
compared to the phone version)

**Comment by kichappa** [comment]
Just to add to @ars4l4n 's points, as a hobby based designer, making new stickers are only on a need basis for me. Whenever I need a single sticker, I am forced to create a whole pack which is redundant. The sticker picker is very unintuitive for both the creators and the average user.

**Comment by andresvanegas19** [comment]
> > > Any updates? It's been a year
> > 
> > 
> > Third-party stickers are supported by WhatsApp web/Desktop since November 2019 😅
> 
> Oh, I was looking for adding custom `.webp` files as a sticker through WhatsApp Web. Any ideas if that is available?

I've been looking for days to see if there's a way to send it but I see that it's not possible :(

So there's no way to send a sticker via whatsapp desktop?

**Comment by kichappa** [comment]
> > Oh, I was looking for adding custom `.webp` files as a sticker through WhatsApp Web. Any ideas if that is available?
> 
> I've been looking for days to see if there's a way to send it but I see that it's not possible :(
> So there's no way to send a sticker via WhatsApp desktop?

So, I have learnt a way to add `.webp` files using a files manager and 2 Whatsapp accounts and collection of stickers that are exclusively stored in one of the accounts. WhatsApp Web uses the servers to render the stickers, so I don't think that will be possible via Web.

**Comment by jaitra1264** [comment]
How do add new stickers to web whatsapp?

**Comment by andresvanegas19** [comment]
> > > Oh, I was looking for adding custom `.webp` files as a sticker through WhatsApp Web. Any ideas if that is available?
> > 
> > 
> > I've been looking for days to see if there's a way to send it but I see that it's not possible :(
> > So there's no way to send a sticker via WhatsApp desktop?
> 
> So, I have learnt a way to add `.webp` files using a file manager, 2 Whatsapp accounts and collection of stickers that are exclusively stored in one of the accounts. WhatsApp Web uses the servers to render the stickers, so I don't think that will be possible via Web.

thanks

**Comment by kichappa** [comment]
> How do add new stickers to web WhatsApp?

Ask your friend to send you a sticker you do not have, then, go to `Internal Storage/WhatsApp/Media/WhatsApp Stickers`, and copy the filename of this new sticker. Now, replace that sticker with the new `.webp` sticker file, close and clear cache of the WhatsApp app.  Reopen, you'll see that the stick you were sent is now different. Add it you your favourites, and viola!

**Comment by Havenard** [comment]
My WhatsApp for Desktop doesn't show favorite stickers, only this thing: https://i.imgur.com/f3CWr6Y.png
What do I do?

**Comment by jaitra1264** [comment]
I have the same problem

**Comment by kichappa** [comment]
> My WhatsApp for Desktop doesn't show favorite stickers, only this thing: https://i.imgur.com/f3CWr6Y.png
> What do I do? Same with WhatsApp Web, tested on two devices.

Same here. Please add favourites stickers to Web.

**Comment by thiagosperandio** [comment]
Same here. Please add favourites stickers to Web.

**Comment by DavidBitner** [comment]
> Same here, only the recent ones and the "categories" in the tabs

Same here

**Comment by Kmfernan5** [comment]
https://gadgets360.com/internet/news/whatsapp-web-custom-sticker-maker-rollout-desktop-how-to-use-2622978#:~:text=Open%20WhatsApp%20Web%2C%20go%20to,computer%20to%20edit%20and%20customise.

**Comment by gaguiarandreani** [comment]
C'mon guys just add the freaking stickers!

**Comment by gaguiarandreani** [comment]
Hire me and I will add them for you!

**Comment by ungarmichael** [comment]
still waiting for this feature ...

**Comment by Gabriele-LS** [comment]
Waiting for this feature, too

**Comment by hyperdynexact** [comment]
Not sure if this is still relevant, but I was looking for this solution today.  And like the rest of you I couldn't find any info about adding stickers to the whatsapps desktop app version.  So here is my own solution.  This is for the Whatsapp Desktop App.

Connect your phone to your PC (i'm using windows 11, but any version shoud be ok)

Create a new folder on your desktop (any name)

Then navigate to this directory on your phone. "This PC\YOURPHONE\Internal storage\Android\media\com.whatsapp\WhatsApp\Media\WhatsApp Stickers" (no quotes)

Copy all or just the stickers you require to the new folder on your desktop.  The sticker files will be in .WEBP format.

Now you need to convert your stickers to an image format.  I use File Converter (https://file-converter.io/), but any file converter will do (on-line or otherwise).  I converted my stickers to .PNG, but you can use .JPG if you like.

Once coverted to the new format .PNG, I deleted the .WEBP files just to keep things tidy (you don't have too).

Now go to your Whatsapp desktop app on your PC.

Any contact will do, look for the smilly face next to paperclip and click it.

Smilly face menu will showup, click STICKERS at the top of the menu.

At the bottom of that menu click the plus symbol "+".

Then navigate to the new folder on your desktop were you saved your converted files. 

Unfortunately you can only select one sticker at a time, so you will have to repeat the process for each additonal sticker).  Select the sticker you would like.

An edit window will showup were you can make size adjustments (I left this as is).

Now click the check mark at the top of the edit window.  Another edit window will showup were you can make additionall edits (again I left this as is).

Click the check mark on the bottom right (green check mark symbol).

The new sticker will apper in the stickers menu.

Now, when you come out of the sticker menu and go back in you will notice your sticker is missing, DON'T PANIC!
Click the star at the bottom of the sticker menu and you will find it there.  Once you have sent your new sticker to a contact it will now show up in the sticker menu as normal (no need to click the star).  

It's a long how-to, but it works.

Hope that helps.

(WHATSAPP, when your ready.  Could you make it a bit easyer for your users, please.)
