### ISSUE TITLE
Non riesco a creare l'app

### ISSUE THREAD

**Issue by clarillaWA** [WhatsApp/stickers#246]
Salve
ho creato un ramo dal master, ho caricato le immagini, ma non riesco a capire dove devo andare per creare l'app di cui si parla nelle varie descrizioni.
Grazie

**Comment by Zandor300** [comment]
This is an English 'forum'. You should translate your question and title into English on your own. Not everyone is going to translate your messages and asking them in English will make your question reach a broader audience.

As for your (Google Translated) question; Please be more specific. Are you using iOS or Android? (also update your title to include either `[iOS]` or `[Android]`). You have to update the JSON file and make it point to your sticker files. Then you have to change your Bundle ID to something of your own. All this is also explained in the platform-specific readme's:  
https://github.com/WhatsApp/stickers/blob/master/Android/README.md  
https://github.com/WhatsApp/stickers/blob/master/iOS/README.md

**Comment by clarillaWA** [comment]
thank you!

**Comment by Zandor300** [comment]
This is a different question and you should have created a new issue.

As to help you out anyway; that is a warning that the methods used are deprecated. That is because the YYImage library hasn't been updated yet to use the new PHPhotoLibrary. (See https://developer.apple.com/documentation/assetslibrary/alassetslibrary). You are able to ignore this as the sample app works and runs just fine but if you really want to get rid of the warning, use the PHPhotoLibrary or ask for help over at https://github.com/ibireme/YYImage.

**Comment by simonzhexu** [comment]
Thank you @Zandor300 for moderating this forum. 

Appreciate your work. 

WhatsApp team
