### ISSUE TITLE
If everyone can just download "Stickers By Me" app on Android why would anyone feel like making Sticker Packs?

### ISSUE THREAD

**Issue by enzyme69** [WhatsApp/stickers#290]
**Specifications**  
OS Level: iOS 12.1.1
Device Manifacture: Apple

**Stickers**
Why would anyone make sticker packs, if someone could just steal your works and make "Stickers By Me".

**The problem**  
Concerning "Stickers By Me" on Android 

**How anyone may be able to reproduce the problem**  
I have friends sending Stickers via Android and all of them says "Stickers By Me".

What if some users started to make pornographic stickers using "Stickers By Me" would that developer get suspended?

**Comment by Zandor300** [comment]
I personally think this is exactly why the WhatsApp team decided to make stickers available by developers making an app for it.

**Comment by simonzhexu** [comment]
Please share the url that links to the "Stickers By Me" app. WhatsApp is a platform for people to send media, we don't police the copy right of the media, and we can't.

**Comment by MarsVard** [comment]
@bansicloud we should just shut down all sharing services where users can share user generated data privately because there is now way of countering that.

Since you know... You dont want WhatsApp to read your messages. The same pornographic material can be an image or a video instead if a sticker.

**Comment by bansicloud** [comment]
@MarsVard No. There is allocation in the law for moderation. And yes some platforms have shut down or changed their policies: the most famous or pertinent right now is Tumblr after saying for years that they would not moderate pornographic content.

To be clear: I don't make sticker apps just pointing out to a fellow developer that we live in a society and there are laws that we all have to take into account while we pursue our tech. I actually found out about your app because of that feature: I tapped on the sticker and View More brought me to your app. I would highly recommend that you introduce a moderation feature that is not entirely AI based. 

The main difference that the law also takes into account is intent: did the platform or app creator know or was made aware of that their program is being used to propagate illicit content. And there is a BIG difference between an image or video or a sticker with no attribution and one where it links back to someone's app and is being used to get more downloads/likes/etc.

I hope other github users find this information useful when considering the approach to take in making sticker apps. If you need to further this discussion, PM me.

**Comment by MarsVard** [comment]
But the users are not storing anything on my servers or anywhere else thay allows me to moderate + the app even works totally offline.
This is like asking Photoshop to have moderation.

And encryption in WhatsApp won't allow WhatsApp to do any moderation as well. And im pretty sure they don't want to either. Imagine whatsapp blocking photos based on the content.

**Comment by bansicloud** [comment]
@MarsVard First off: I think your concept IS innovative and SHOULD be explored more. After all it is decentralization which is good for the internet(duh!). That being said, I am deeply involved in LegalTech and from that vantage point I can clearly say that there are a lot of issues that would crop up. The worse thing that could happen is that you or anyone else spends all this time and effort creating the best app that they can and then some crusader files a complaint with Google, Apple, WA-FB or worse authorities and you get shut down or in some legal issues.

So here is what I would say: based on a reading of SESTA-FOSTA, since the stickers as of now do link directly to your app or the other developer's app, and that illegal content is being used to "drive" downloads, including but not limited to pornography, copyrighted items under DMCA, etc., the defense that the content does not reside on your servers is not strong. After all, your app is being used as a MEDIUM for the illegal acts. So even if you did remove the link back to your app, people are still using your app to spread illegal content. Think about GDPR and the concept of data controllers and data processors. I am NOT saying that this applies here but merely to point out that there are different levels of liability:

1. Hosting illegal content,
2. Promoting illegal content by being a medium,
3. Gains from illegal content.

As far as the general liability of WA etc, they are a much bigger corp. But even there we know they WILL be regulated: https://www.bloomberg.com/news/articles/2018-12-06/australia-moves-toward-passing-law-targeting-whatsapp-signal. BTW this is just the tip of the iceberg. I know that in France and Germany, there are similar laws being crafted as we speak. 

Again: I think the value that this issue has had is best taken off github since we may be drifting a bit and I dont want to be seen as spamming. I wanted to call your attention and the attention of other developers so that they dont fall into the trap and think about how certain features could be installed to combat these. 

I know of a few tech solutions that could be used using open source software. So again, DM me to take this conversation further. I am also engaged in other things so as much as I would love to help you out(look at these LONG posts LOL) I may not be able to. Let us see. I personally do use WA stickers as they help me express a lot of feelings-emotions that are sometimes hard for me to type out.

**Comment by MarvinJWendt** [comment]
Hey,
This Issue seems to be inactive. To keep things organized I will close this for now. If this Issue is still relevant, don't hesitate to drop a comment and I will reopen it if necessary.

Sincerely,
Marvin Wendt
