### ISSUE TITLE
Play Store link.

### ISSUE THREAD

**Issue by Zerlingg** [WhatsApp/stickers#327]
**The problem**  
How can i add a link that is not from the Play Store for the app. I cant pay the 25$ they ask so i wanna upload it to any other web so people can download it, but i dont know how to add the link so people when they press the sticker they can go to the website :(... theres any way to do it?

**Comment by simonzhexu** [comment]
Sorry, we don't provide a mechanism to go to other website. We only allow play store link in order to prevent our users to go to fishy/spammy website when clicking on stickers. In your case, you can leave the play link empty. It will not allow your sticker to launch to a website to download, it will at least let your sticker pack app pass the validation.
