### ISSUE TITLE
Generate Signed APK error

### ISSUE THREAD

**Issue by kinorth** [WhatsApp/stickers#356]
in build.gradle(APP) the line: 
"throw new GradleException("applicationId in defaultConfig cannot start with com.kijooj, please change your applicationId in app/build.gradle");"  (checkRelease)

This is an error when it comes to generating Signed APK, I can simply remove it? 
or can I have any future problems?

@simonzhexu 

sorry for my bad English

**Comment by MarvinJWendt** [comment]
Hey @kinorth 
rth,
The code you posted isn't actually in the repo.
There are two errors of this kind:  

First:
```java
if (android.defaultConfig.applicationId.startsWith("com.whatsapp")) {
throw new GradleException("applicationId in defaultConfig cannot start with com.whatsapp, please change your applicationId in app/build.gradle");
}
```

Second: 
```java
if (android.defaultConfig.applicationId.startsWith("com.example")) {
throw new GradleException("applicationId in defaultConfig cannot start with com.example, please change your applicationId in app/build.gradle");
}
```

Those two checks are used so that you won't publish your app with the package name of WhatsApp or an template example.

To me it seems like you used `replace all` for your applicationId.

To fix your issue, make sure that those lines are **not** changed!

1. https://github.com/WhatsApp/stickers/blob/1a9f00222f96779e50b0269e58a9bb79b10221fa/Android/app/build.gradle#L44-L46
2. https://github.com/WhatsApp/stickers/blob/1a9f00222f96779e50b0269e58a9bb79b10221fa/Android/app/build.gradle#L68-L70

If they are changed, just copy the original and overwrite them.

Let me know if you have any further questions :)

**Comment by kinorth** [comment]
Thank you
