### ISSUE TITLE
[Android] Remove "view more" button

### ISSUE THREAD

**Issue by Sparklester** [WhatsApp/stickers#391]
I found some people using stickers with no "view more" button. How do you do that?

**Comment by simonzhexu** [comment]
no play store url -> no view more

**Comment by Sparklester** [comment]
> no play store url -> no view more

Removing the link in the smali file between quotes after  `const-string p1,` causes the error "There's a problem with this sticker pack and it can't be added to WhatsApp". This error shows up whenever there is no link, or the link isn't to a Google Play app.

**Comment by simonzhexu** [comment]
please be more specific. There is no const-string p1 in the sample app.

**Comment by Alex193a** [comment]
@simonzhexu he is trying to remove the play store link by decompiling the app and modifying the byte code directly.
I think it's not necessary to provide further help because his intent is to modify someone else's app without permission, otherwise he would have had access to the source code of the app in question.
