### ISSUE TITLE
PUP.HighConfidence detected  

### ISSUE THREAD

**Issue by rabindramarndi1** [WhatsApp/stickers#407]
while i checking the app at virustotal im gettim this error. is tht  dengarious for device?

**Comment by MarvinJWendt** [comment]
Hey @rabindramarndi1,
The source code provided here is totally fine. PUP stands for `Potentially Unwanted Program`.
`HighConfidence` means that a virus scanner thinks that something "looks strange" in the app.
If you're compiling to Android, it's probably because the source code will get obfuscated when you compile the APK.
