### ISSUE TITLE
Brand guidelines: using "for WhatsApp" in the app's title

### ISSUE THREAD

**Issue by nApps4UI** [WhatsApp/stickers#479]
Instagram's guidelines state 

> If you offer an app, website or a product or service that uses the Instagram APIs or is otherwise compatible with or related to Instagram, you may only use Instagram to say that your app is "for Instagram" or that the name of your campaign is "on Instagram" in a descriptive manner.

and I would much appreciate the same for WhatsApp. Unlike on the Play Store, the App Store search does not include the app's description but only the title, subtitle, keywords and the company's name. The lucky few who got "X Sticker Maker for WhatsApp" in their titles passed by App Review get seen by people looking for "WhatsApp Stickers". BUT the honest ones who have only tagged their apps with "WAStickerApps" obviously never get seen on the App Store because it's utopian to think that anyone would type "WAStickerApps" in the App Store search when looking for WhatsApp stickers. 

Please add a similar phrase to your brand guidelines like Instagram did so we can finally tag our apps accordingly. Or make a "subtitle" rule for that matter. You and Instagram are both owned by Facebook so I don't think there would be much conflict of interest about it.

**Comment by simonzhexu** [comment]
I understand your pain. I will bring up with our team and see if there is anything we can do there.

**Comment by nApps4UI** [comment]
Hello Simon, thanks a lot for your reply. I very much appreciate your help. Just to add to this: the **name** of our apps, our own trademarks etc. will suffice without the "for WhatsApp" suffix. It's just about the **title** field in the Store listings. The title usually has some additional info (e.g. "Music to Video Converter") in it - there will absolutely be no confusion with your brand as there are many "for X" apps on the Store and people understand that those are third-party apps.

We do not want to trick people into thinking we are affiliated with you. We only want our apps to be found on the Store. Including the proposed phrase to your guidelines could easily save our developer accounts. It would mean a lot to us.

Thank you for your help.

**Comment by nApps4UI** [comment]
Hey Simon, any update on this? My app is online, but due to the name, stuck in rejections now and I can't upload any updates. Apple allows these "for Instagram" apps because people can direct them to the guidelines. Adding this to the WhatsApp guidelines would help so much here.

**Comment by Zandor300** [comment]
@simonzhexu

**Comment by jackengine** [comment]
I found guideline for WhatsApp business here https://whatsappbrand.com/ that stats that brands can use WhatsApp word with two capital letters with their contents. What make big issue is when play store suspend your app in regards of complaint from your third party brand protection service, for using "WhatsApp" like this XXX - Whatsapp Sticker Maker, and then play store do not re-consider it up to termination of developer's play store account, which makes him losing money, users of other app in his account, reviews, purchases. 

You replied that you will discuss what you can do. I think you should try that developer that has apps suspended apps (Which do not allow developer to edit anything.) in their playstore accounts just because little "a" in "Whatsapp", help to restore it, by mailing through same service you used to block or by directly your legal team, so that developer can edit and restore it.

**Comment by nApps4UI** [comment]
Unfortunately it's not that. My app had W and A capitalized and Apple as well as Google are on the verge of banning my accounts/ my primary source of income/ the hopes and dreams of my family.

There are so many Instagram apps that don't get banned because they can state the guideline, I beg you to add such a phrase for the WhatsApp guidelines as well.

**Comment by simonzhexu** [comment]
I am sorry that this is happening. It is being discussed internally. In the mean time, I suggest you play it safe and follow the rules. We already promote sticker apps in the sticker store via a link to the play store. Also, users can download the app if they receive a sticker from others. Make sure you put in the android link on contents.json.

**Comment by KeizerDev** [comment]
Any update on this?

**Comment by jackflyer** [comment]
We are developers - what we do whole day? - find issue, discuss on it, solve it. PlayStore and AppStore  both have straight behavior, just suspending app. We all developers are not in the habit of searching policies over google, especially when demo apps are provided. Please add link to WhatsApp brand https://whatsappbrand.com/  Policy link on top of Get Started section of repository. And do something to help developers to restore such apps, play store listens this kind of issues when complainant helps them. 
This issue should be on priority, because it's affects more developers using this repository.

**Comment by simonzhexu** [comment]
Hello, @jackflyer , thank you for your suggestion. I have put the WhatsApp brand website on the repo. I am discussing this with legal.

**Comment by UmarCoder-lab** [comment]
Hi, please i need your help. Please can i use "Status Saver for Whatsapp : Status Saver Downloader Status Saver app" as my playstore title. I did it like that and playstore suspended my app. At the discription of my app i even wrote "IMPORTANT
This application is not affiliated, sponsored or endorsed by WhatsApp Inc.
We are not responsible for any type of reuse of the media downloaded by the user." Please help me because that's the source of income to me and my family.Thank you.

**Comment by Zandor300** [comment]
@UmarCoder-lab No, you cannot use WhatsApp in the title of your application. If you do, you will most likely receive a take down notice.

Instead, you can use WhatsApp in the description of your application.

From README.md:

> When naming your app, it is strongly advised you do not use "WhatsApp" anywhere in the name of your app or in the name field of your app listing. However, when preparing your app for submission in Google Play Store/App Store, you'll have the option to add description associated with your app and it's okay to mention WhatsApp in the description. Make sure you use "WhatsApp" as a brand name, with "W" and "A" capitalized with no space between letters. More information on WhatsApp Brand(https://whatsappbrand.com/).

**Comment by UmarCoder-lab** [comment]
Thanks sir
