### ISSUE TITLE
app Update Rejected [Android]

### ISSUE THREAD

**Issue by Darsh23** [WhatsApp/stickers#529]
first i make Content rating for my app +12 ( littel nudity , littel violate ) and pass , but when try to push an packs update it rejected and i try to add privacy policy page but also reject as  Content rating is wrong
what should i do ?

" Your app’s content rating is incorrect. Our content rating system includes official ratings from the International Age Rating Coalition (IARC) and is designed to help developers communicate locally relevant content ratings to users. "

**Comment by MarvinJWendt** [comment]
Hey @Darsh23, it seems like Google wants you to rate your app stricter. Violence and nudity probably shouldn't be rated for 12+. Maybe 16+ or even 18+. Depends on what your stickers show.

**Comment by ar-arvind** [comment]
Hi @Darsh23, You app content rating may be incorrect, refer the following link to learn more about choosing relevant content rating for your app.
https://support.google.com/googleplay/android-developer/answer/188189?hl=en

If you believe your app was **rejected in error**, you can contact **Google Support Team** for a appeal via chat or email using below link.
https://support.google.com/googleplay/android-developer/answer/7218994?hl=en

**Comment by Zandor300** [comment]
@Darsh23 Did you get any further with the help that has already been provided?

**Comment by hariiprasad** [comment]
@Darsh23 if you are using admob ads. Block all 18+ ads and check once.

**Comment by MarvinJWendt** [comment]
It seems like all questions are answered. There hasn't been any recent activity here, so I would say the issue is resolved. If you have any further questions on this Issue don't hesitate to drop a comment and I will reopen the Issue if necessary. 
Have a nice day 😄

**Comment by incappgame** [comment]
please help i have same problem

Publishing status: Rejected
--
Your app has been rejected and wasn't published due to a policy violation. If you submitted an update, the previous version of your app is still available on Google Play.


Issue : Incorrect content rating
Your app’s content rating is incorrect. Our content rating system includes official ratings from the International Age Rating Coalition (IARC) and is designed to help developers communicate locally relevant content ratings to users.
