### ISSUE TITLE
[Android] Android Third party keyboard Sticker Send support for Whatsapp

### ISSUE THREAD

**Issue by nickyfantasy** [WhatsApp/stickers#619]
Hi, 
   I am building a third party android keyboard. I saw GBoard and Bobble Keyboard are able to send sticker FROM the keyboard and sticker will be displayed in Whatsapp without having another preview screen. 

Integration such as what described in following link:
https://wabetainfo.com/whatsapp-will-allow-stickers-integration-for-third-party-keyboards/

I am wondering if such API for android keyboard is opened to public?

Thanks, 
Nicky

**Comment by MarvinJWendt** [comment]
Hi @nickyfantasy, I am sorry to tell you that WhatsApp employees are not allowed to talk about future features of WhatsApp.

**Comment by krunalOrigin** [comment]
I have create my custom sticker pack and save it when ever i add to sticker on whatsapp getting this two error
1) There's a problem with this sticker pack and it can't be added to WhatsApp
2) third party pack cannot be found likely because the corresponding app is restricted, sdk :28,power saving mode : false

this is my custom create json files
{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "avoid_cache": false,
      "identifier": "temp",
      "image_data_version": "100",
      "license_agreement_website": "",
      "name": "Temp",
      "privacy_policy_website": "",
      "publisher": "Origin",
      "publisher_email": "",
      "publisher_website": "",
      "stickers": [
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_0.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_1.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_2.webp"
        }
      ],
      "tray_image_file": "temp.webp"
    }
  ]
}

**Comment by benallpass** [comment]
@nickyfantasy The API is indeed open to the public. You should check the editor info for the mime type `image/webp.wasticker` and share a WebP like you would an image/gif (I believe it has the same size/dimension restrictions listed [here](https://github.com/WhatsApp/stickers/tree/master/Android)).
