### ISSUE TITLE
README ambiguity on sticker art format (WebP or PNG?)

### ISSUE THREAD

**Issue by ansonl** [WhatsApp/stickers#626]
**Specifications**  
OS Version: All
Device Manufacturer: All

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
The README.md says 
> Stickers must be either in PNG or the WebP format.

as well as 

> Your sticker art must be in the WebP format. 

The premade issue checkboxes above mention both WebP and PNG. Which is it? Can the actual sticker art data (base64) be either WebP or PNG? Or does the 512x512 sticker art have be WebP format only when converted to base64 for the sticker pack JSON payload. Thank you. 

**Reproduction Steps**  
See iOS page README.md.

**Head of Commit**
32ae6e5ed128569781187d77e3b628eeffac0f9e

**Links**  
https://github.com/WhatsApp/stickers/blob/master/iOS/README.md

**Comment by Zandor300** [comment]
If I believe this correctly, stickers are required to be in the WEBP format on Android. They can be either PNG or WEBP on iOS. The [Android README.md](https://github.com/WhatsApp/stickers/blob/2dfb43629dd83600a9596f299d4a3fbac62ba7a7/Android/README.md) is mentioning that WEBP is required twice where the [iOS README.md](https://github.com/WhatsApp/stickers/blob/2dfb43629dd83600a9596f299d4a3fbac62ba7a7/iOS/README.md) is mentioning different things.

I think this might have been caused because the text was copied from the Android version?
