### ISSUE TITLE
[Android] countries control to roll out

### ISSUE THREAD

**Issue by BattleShipPark** [WhatsApp/stickers#745]
**Problem Description**  
You plan to roll out to Brazil, Indonesia and Iran first. How do you control those countries?
If you control that in PlayStore(which means you release only in the specified countries) I need to release my app only in the specified countries, and if you control that with server configuration such as Firebase RemoteConfig I need to release my app in all the countries and control it with server configuration.
I want to let rules to distinguish countries be same between you and me. If rules are different, my app will try to export animated stickers even though you don't support animated stickers.

Thanks.

**Comment by Dwite** [comment]
I'm not affiliated or anyhow related to WhatsApp, but historically they did such changes using feature flags and backend configuration of them. So I would assume that this time it will be the same, I would still suggest to develop a fail path scenario that shows some explanation when user tries to export animated stickers, but it fails due to some reasons.

**Comment by simonzhexu** [comment]
Hi @BattleShipPark , we don't rely on play store to control country roll out. as @Dwite  mentioned, we rely on a server configuration that controls what features are available on client side. I suggest you release your app to only these countries first in Play Store.

**Comment by BattleShipPark** [comment]
Hi @simonzhexu ,
I am worried about when Play Store's Brazil is different from your server configuration's Brazil. Then I have two cases:
1. My users can create animated stickers but WA is not enabled.
2. My users can not create animated stickers but WA is enabled.
Case 2 is not the problem but Case 1 is. Users will have poor experiences because they have "This WA does not support animated stickers" whenever they try to add stickers to WA. Then they rate my app with 1 star... 😱 

What about this? if you can provide API to check WA is enabled or not for animated stickers, I can provide better experience to users.
Animated stickers are not easy for both WA and 3rd-parties... 😢

**Comment by simonzhexu** [comment]
> Hi @simonzhexu ,
> I am worried about when Play Store's Brazil is different from your server configuration's Brazil. Then I have two cases:
> 
> 1. My users can create animated stickers but WA is not enabled.
> 2. My users can not create animated stickers but WA is enabled.
>    Case 2 is not the problem but Case 1 is. Users will have poor experiences because they have "This WA does not support animated stickers" whenever they try to add stickers to WA. Then they rate my app with 1 star... 😱
> 
> What about this? if you can provide API to check WA is enabled or not for animated stickers, I can provide better experience to users.
> Animated stickers are not easy for both WA and 3rd-parties... 😢

Hi @BattleShipPark , we will turn the settings on for all Brazil phone numbers. that's a good suggestion. I have not been able to prioritize that work, perhaps you can give your users a heads up that WhatsApp may not work for animated stickers due to reasons that WhatsApp may not have turned on the configuration.

**Comment by BattleShipPark** [comment]
@simonzhexu Thanks
