### ISSUE TITLE
Stickers cannot be added to Business WhatsApp[Android]

### ISSUE THREAD

**Issue by AbdullahProgrammer426351** [WhatsApp/stickers#896]
When I try to add stickers on Business Whatsapp, a dialog opens and gives me an error : 

> There's a problem with this sticker pack and it can't be added to Business Whatsapp

And when I click ok
Another dialog appears with the message 

> Error with the Pack:
Permission denial : reading com.example.xxx.stickercontentprovider/metadata/2 from pid=7454, uid=10047 requires com.whatsapp.sticker.READ or grantUriPermission()

**Comment by Korogba** [comment]
This is likely because you have not setup your [ContentProvider](https://developer.android.com/guide/topics/providers/content-provider-basics) correctly. 

You can check the docs here to see how this is done in the sample app: https://github.com/WhatsApp/stickers/blob/main/Android/README.md#advanced-development
