### ISSUE TITLE
Third party pack cannot be found likely because the corresponding app is restricted !!!

### ISSUE THREAD

**Issue by ThucVan** [WhatsApp/stickers#903]
I got this error at android version 11, earlier same error happened on Dec 14, 2019 but i couldn't find the solution
Help me!!!

**Comment by Korogba** [comment]
This is likely because you have not setup your [ContentProvider](https://developer.android.com/guide/topics/providers/content-provider-basics) correctly. 

You can check the docs here to see how this is done in the sample app: https://github.com/WhatsApp/stickers/blob/main/Android/README.md#advanced-development
